version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sq1dev
      MYSQL_DATABASE: demo_tracker
    volumes:
      - ./docker/mysqldata:/var/lib/mysql
      - ./docker/mysql/createDevDB.sql:/docker-entrypoint-initdb.d/init1.sql
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/DockerfilePHP
      args:
        buildno: 1.0
    ports:
      - 8087:80
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - "db"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: sq1dev
    ports:
      - "8089:80"
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
